# Generated by Django 5.2.5 on 2025-09-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_available_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['user__first_name']},
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_time_end',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_time_start',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
